using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Xunit;

namespace HanziLookup.Tests;

/// <summary>
/// Tests for the digits / Latin letters / punctuation repository (<c>data/alnum.json</c>) and for
/// matching against a merged Chinese + alphanumeric repository.
/// </summary>
/// <remarks>
/// <para>
/// The repository is generated by <c>tools/data/build_alnum.py</c> from the stroke templates in
/// <c>tools/data/alnum_templates.py</c>; there is no public stroke-order corpus for Latin letters, so
/// the templates are authored. What matters for the library is that the file has the same shape as
/// <c>mmah.json</c>, that every entry can actually be scored, and that handwriting comes back as the
/// character that was written.
/// </para>
/// </remarks>
public sealed class AlphanumericDataTests
{
    private static HanziData Alphanumeric() => HanziData.Load(TestPaths.Require(TestPaths.AlphanumericFile, "alnum.json"));

    private static HanziData Chinese() => HanziData.Load(TestPaths.Require(TestPaths.DataFile, "mmah.json"));

    [Fact]
    public void RepositoryHasTheExpectedShape()
    {
        var data = Alphanumeric();

        Assert.Equal(72, data.Count);
        Assert.All(data.Characters, character => Assert.Equal(1, character.Character.Length));

        foreach (var expected in new[] { "0", "5", "9", "A", "Z", "a", "z", "+", "/" })
        {
            Assert.NotNull(data.Find(expected));
        }
    }

    [Fact]
    public void EveryEntryCanBeScored()
    {
        var data = Alphanumeric();

        foreach (var character in data.Characters)
        {
            var bytes = data.GetSubStrokeBytes(character);
            Assert.Equal(character.SubStrokeCount * 3, bytes.Length);

            for (var i = 0; i < character.SubStrokeCount; ++i)
            {
                var length = bytes[i * 3 + 1];
                var center = bytes[i * 3 + 2];

                // A stored length of 0 makes GetLengthScore return NaN, so the character could never
                // match anything; a centre of 0 is the packed format's "no centre".
                Assert.True(length > 0, $"'{character.Character}' sub-stroke {i} has length 0");
                Assert.True(center > 0, $"'{character.Character}' sub-stroke {i} has no stored centre");
            }
        }
    }

    [Fact]
    public void StrokeCountsAreSane()
    {
        var data = Alphanumeric();

        // "I" is one straight stroke, "W" is one continuous stroke, "H" is three.
        Assert.Equal(1, data.Find("I")!.Value.StrokeCount);
        Assert.Equal(1, data.Find("W")!.Value.StrokeCount);
        Assert.Equal(3, data.Find("H")!.Value.StrokeCount);
        Assert.True(data.Find("8")!.Value.SubStrokeCount >= 2);
    }

    /// <summary>
    /// The templates are skeleton drawings, so <see cref="StrokeSkeleton"/> has to reconstruct
    /// something recognisable from them - this is what the demo's candidate preview draws.
    /// </summary>
    [Fact]
    public void SkeletonCanBeReconstructed()
    {
        var data = Alphanumeric();

        foreach (var name in new[] { "0", "4", "A", "M", "g", "8" })
        {
            var entry = data.Find(name)!.Value;
            var skeleton = StrokeSkeleton.FromRepositoryCharacter(data, entry);

            Assert.Equal(entry.SubStrokeCount, skeleton.Count);
            Assert.All(skeleton, segment =>
            {
                Assert.InRange(segment.Start.X, -1.5, 1.5);
                Assert.InRange(segment.Start.Y, -1.5, 1.5);
                Assert.InRange(segment.End.X, -1.5, 1.5);
                Assert.InRange(segment.End.Y, -1.5, 1.5);
            });
        }
    }

    /// <summary>
    /// Writing a glyph has to bring it back.  The coordinates are the stroke templates from
    /// <c>tools/data/alnum_templates.py</c> (unit box x 256), written as
    /// <c>"x,y x,y | x,y"</c> - spaces separate points, a pipe separates strokes.  They are written
    /// by <see cref="StrokePreprocessingTests.Hand"/> first, so the input is a shaky, unevenly
    /// sampled version of the template rather than the template itself.  The expected outcomes were
    /// verified with the mirror of that sampler in <c>tools/data/</c> before being written down here.
    /// </summary>
    [Theory]
    [InlineData("4", "158.72,46.08 122.88,102.4 76.8,143.36 56.32,163.84 117.76,163.84 199.68,163.84 | 158.72,46.08 158.72,133.12 158.72,204.8")]
    [InlineData("7", "66.56,46.08 128,46.08 189.44,46.08 | 189.44,46.08 158.72,117.76 128,168.96 97.28,204.8")]
    [InlineData("L", "76.8,46.08 76.8,125.44 76.8,204.8 133.12,204.8 184.32,204.8")]
    [InlineData("A", "56.32,204.8 92.16,125.44 128,46.08 163.84,125.44 199.68,204.8 | 84.48,148.48 128,148.48 171.52,148.48")]
    [InlineData("S", "179.2,66.56 148.48,46.08 102.4,48.64 76.8,76.8 84.48,110.08 128,125.44 168.96,140.8 184.32,171.52 158.72,199.68 107.52,204.8 74.24,186.88 69.12,168.96")]
    public void HandwrittenGlyphIsRecognized(string expected, string strokes)
    {
        var matcher = new Matcher(Alphanumeric());
        var drawn = ParseStrokes(strokes).Select(stroke => StrokePreprocessingTests.Hand(stroke));
        var paths = StrokePreprocessor.Process(drawn);

        var results = matcher.Match(AnalyzedCharacter.FromStrokes(paths), 5);

        Assert.Equal(expected, results[0].Character);
    }

    /// <summary>
    /// A round glyph is recognized, but which round glyph is a toss-up: the matcher normalizes every
    /// character by its own bounding box, so "0", "O" and "o" are one shape.  The test pins the real
    /// behaviour instead of pretending otherwise - the character has to be in the list, and the
    /// neighbours are the same round glyphs.
    /// </summary>
    [Fact]
    public void RoundGlyphIsRecognizedEvenThoughItsCaseIsNot()
    {
        var matcher = new Matcher(Alphanumeric());
        const string zero = "133.12,48.64 174.08,71.68 189.44,107.52 184.32,158.72 153.6,194.56 "
                            + "112.64,204.8 76.8,189.44 66.56,148.48 76.8,97.28 102.4,61.44 120.32,53.76";
        var drawn = ParseStrokes(zero).Select(stroke => StrokePreprocessingTests.Hand(stroke));

        var results = matcher.Match(AnalyzedCharacter.FromStrokes(StrokePreprocessor.Process(drawn)), 5);

        Assert.Contains("0", results.Select(match => match.Character));
        Assert.All(
            results.Select(match => match.Character).Take(3),
            character => Assert.Contains(character, new[] { "0", "O", "o" }));
    }

    /// <summary>Parses <c>"x,y x,y | x,y"</c> into strokes.</summary>
    private static IReadOnlyList<IReadOnlyList<StrokePoint>> ParseStrokes(string notation)
    {
        var strokes = new List<IReadOnlyList<StrokePoint>>();
        foreach (var stroke in notation.Split('|', StringSplitOptions.TrimEntries))
        {
            var points = new List<StrokePoint>();
            foreach (var pair in stroke.Split(' ', StringSplitOptions.RemoveEmptyEntries))
            {
                var parts = pair.Split(',');
                points.Add(new StrokePoint(
                    double.Parse(parts[0], CultureInfo.InvariantCulture),
                    double.Parse(parts[1], CultureInfo.InvariantCulture)));
            }

            strokes.Add(points);
        }

        return strokes;
    }

    /// <summary>A vertical stem is "I" - and "1" and "l" follow closely, which is the point.</summary>
    [Fact]
    public void VerticalStemIsRecognizedAsI()
    {
        var matcher = new Matcher(Alphanumeric());
        var stem = RawStroke.FromCoordinates(new[]
        {
            new[] { 128.0, 46.0 },
            new[] { 128.0, 125.0 },
            new[] { 128.0, 205.0 },
        });

        var results = matcher.Match(
            AnalyzedCharacter.FromStrokes(StrokePreprocessor.Process(new IReadOnlyList<StrokePoint>[] { stem })),
            5);

        Assert.Equal("I", results[0].Character);
    }

    [Fact]
    public void ConcatMergesBothRepositories()
    {
        var chinese = Chinese();
        var alnum = Alphanumeric();
        var merged = HanziData.Concat(chinese, alnum);

        Assert.Equal(chinese.Count + alnum.Count, merged.Count);
        Assert.NotNull(merged.Find("一"));

        // The last entry of the Chinese table, i.e. the one whose offset moves the most.
        Assert.NotNull(merged.Find(chinese.Characters[^1].Character));
        Assert.NotNull(merged.Find("A"));
        Assert.NotNull(merged.Find("+"));
    }

    [Fact]
    public void ConcatRePointsEveryOffset()
    {
        var chinese = Chinese();
        var alnum = Alphanumeric();
        var merged = HanziData.Concat(chinese, alnum);

        // Every entry must read back exactly what it was before the merge.
        foreach (var entry in alnum.Characters)
        {
            var moved = merged.Find(entry.Character)!.Value;
            Assert.Equal(entry.StrokeCount, moved.StrokeCount);
            Assert.Equal(entry.SubStrokeCount, moved.SubStrokeCount);
            Assert.Equal(
                alnum.GetSubStrokeBytes(entry).ToArray(),
                merged.GetSubStrokeBytes(moved).ToArray());
        }

        foreach (var entry in chinese.Characters.Take(50))
        {
            var moved = merged.Find(entry.Character)!.Value;
            Assert.Equal(
                chinese.GetSubStrokeBytes(entry).ToArray(),
                merged.GetSubStrokeBytes(moved).ToArray());
        }

        Assert.Equal(chinese.SubStrokes.Length + alnum.SubStrokes.Length, merged.SubStrokes.Length);
    }

    [Fact]
    public void ConcatKeepsTheFirstRepositoryOnDuplicates()
    {
        var first = new HanziData(
            new[] { new HanziCharacter("A", 1, 1, 0) },
            new byte[] { 0, 200, 0x77 });
        var second = new HanziData(
            new[] { new HanziCharacter("A", 1, 1, 0), new HanziCharacter("B", 1, 1, 3) },
            new byte[] { 64, 100, 0x88, 128, 150, 0x99 });

        var merged = HanziData.Concat(first, second);

        Assert.Equal(2, merged.Count);
        Assert.Equal(new byte[] { 0, 200, 0x77 }, merged.GetSubStrokeBytes(merged.Find("A")!.Value).ToArray());
        Assert.Equal(new byte[] { 128, 150, 0x99 }, merged.GetSubStrokeBytes(merged.Find("B")!.Value).ToArray());
    }

    [Fact]
    public void ConcatOfOneRepositoryIsThatRepository()
    {
        var alnum = Alphanumeric();
        var merged = HanziData.Concat(alnum);

        Assert.Equal(alnum.Count, merged.Count);
        Assert.Equal(alnum.SubStrokes.ToArray(), merged.SubStrokes.ToArray());
    }

    [Fact]
    public void ConcatRejectsNullEntries()
    {
        Assert.Throws<ArgumentNullException>(() => HanziData.Concat((HanziData[])null!));
        Assert.Throws<ArgumentException>(() => HanziData.Concat(new HanziData[] { null! }));
    }

    /// <summary>
    /// With both repositories merged, a Chinese character and a digit are recognized from the same
    /// session - which is the point of merging rather than searching two matchers and merging results.
    /// </summary>
    [Fact]
    public void MergedRepositoryRecognizesBothScripts()
    {
        var merged = HanziData.Concat(Chinese(), Alphanumeric());
        var session = new HandwritingSession(merged, resultLimit: 5);

        // A horizontal bar: 一 in the Chinese set.
        var horizontal = RawStroke.FromCoordinates(new[]
        {
            new[] { 36.0, 128.0 },
            new[] { 130.0, 132.0 },
            new[] { 224.0, 126.0 },
        });
        session.AddStroke(horizontal);

        // Not necessarily first: "-" is the same line and the Latin repository competes for the
        // match.  What matters is that the Chinese character is in the list at all.
        Assert.Contains("一", session.Results.Select(match => match.Character));

        // The same session, a vertical stem: I in the alphanumeric set.
        session.Clear();
        var stem = RawStroke.FromCoordinates(new[]
        {
            new[] { 128.0, 44.0 },
            new[] { 127.0, 140.0 },
            new[] { 129.0, 232.0 },
        });
        session.AddStroke(stem);

        // I is a bare vertical stem, and so are 丨 and l - the Latin one is found, but the order is
        // not guaranteed, and "1" does not even reach the list: its data has a flag and a base that
        // the stem does not have.
        Assert.Contains("I", session.Results.Select(match => match.Character));
    }
}