using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;

namespace HanziLookup.Tests;

/// <summary>
/// The reference data generated by the original JavaScript implementation
/// (<c>hanzilookup-js@1.0.3</c>) - see <c>tools/reference/generate-reference-vectors.mjs</c>.
/// </summary>
internal sealed class ReferenceVectors
{
    public string GeneratedBy { get; init; } = string.Empty;

    public ReferenceDataInfo Data { get; init; } = new();

    public List<double> DirectionScoreTable { get; init; } = new();

    public List<double> LengthScoreTable { get; init; } = new();

    public List<double> PositionScoreTable { get; init; } = new();

    public List<ReferenceCurve> Curves { get; init; } = new();

    public List<ReferenceCase> Cases { get; init; } = new();

    public static ReferenceVectors Load(string path)
    {
        using var document = JsonDocument.Parse(File.ReadAllBytes(path));
        var root = document.RootElement;

        var vectors = new ReferenceVectors
        {
            GeneratedBy = root.GetProperty("generatedBy").GetString() ?? string.Empty,
            Data = new ReferenceDataInfo
            {
                File = root.GetProperty("data").GetProperty("file").GetString() ?? string.Empty,
                CharacterCount = root.GetProperty("data").GetProperty("characterCount").GetInt32(),
                SubStrokeByteCount = root.GetProperty("data").GetProperty("substrokeByteCount").GetInt32(),
                SubStrokeSha256 = root.GetProperty("data").GetProperty("substrokeSha256").GetString() ?? string.Empty
            }
        };

        foreach (var value in root.GetProperty("scoreTables").GetProperty("direction").EnumerateArray())
        {
            vectors.DirectionScoreTable.Add(value.GetDouble());
        }

        foreach (var value in root.GetProperty("scoreTables").GetProperty("length").EnumerateArray())
        {
            vectors.LengthScoreTable.Add(value.GetDouble());
        }

        foreach (var value in root.GetProperty("scoreTables").GetProperty("position").EnumerateArray())
        {
            vectors.PositionScoreTable.Add(value.GetDouble());
        }

        foreach (var element in root.GetProperty("curves").EnumerateArray())
        {
            var curve = new ReferenceCurve
            {
                Name = element.GetProperty("name").GetString() ?? string.Empty
            };

            foreach (var arg in element.GetProperty("args").EnumerateArray())
            {
                curve.Arguments.Add(arg.GetDouble());
            }

            foreach (var sample in element.GetProperty("samples").EnumerateArray())
            {
                var referenceSample = new ReferenceCurveSample
                {
                    X = sample.GetProperty("x").GetDouble(),
                    FirstSolution = ParseScore(sample.GetProperty("getFirstSolutionForX"))
                };

                foreach (var solution in sample.GetProperty("solveForX").EnumerateArray())
                {
                    referenceSample.Solutions.Add(ParseScore(solution));
                }

                curve.Samples.Add(referenceSample);
            }

            vectors.Curves.Add(curve);
        }

        foreach (var element in root.GetProperty("cases").EnumerateArray())
        {
            var referenceCase = new ReferenceCase
            {
                Name = element.GetProperty("name").GetString() ?? string.Empty,
                Note = element.TryGetProperty("note", out var note) && note.ValueKind == JsonValueKind.String
                    ? note.GetString()
                    : null,
                Looseness = element.GetProperty("looseness").GetDouble(),
                Limit = element.GetProperty("limit").GetInt32(),
                CallbackInvoked = element.GetProperty("callbackInvoked").GetBoolean(),
                Expected = new ReferenceAnalysis
                {
                    SubStrokeCount = element.GetProperty("analysis").GetProperty("subStrokeCount").GetInt32()
                },
                Counters = new ReferenceCounters
                {
                    Characters = element.GetProperty("counters").GetProperty("chars").GetInt32(),
                    SubStrokes = element.GetProperty("counters").GetProperty("subStrokes").GetInt32()
                }
            };

            foreach (var bounds in element.GetProperty("analysis").GetProperty("bounds").EnumerateArray())
            {
                referenceCase.Expected.Bounds.Add(bounds.GetDouble());
            }

            foreach (var stroke in element.GetProperty("analysis").GetProperty("strokes").EnumerateArray())
            {
                var referenceStroke = new ReferenceStroke();
                foreach (var pivot in stroke.GetProperty("pivotIndexes").EnumerateArray())
                {
                    referenceStroke.PivotIndexes.Add(pivot.GetInt32());
                }

                foreach (var subStroke in stroke.GetProperty("subStrokes").EnumerateArray())
                {
                    referenceStroke.SubStrokes.Add(new ReferenceSubStroke
                    {
                        Direction = subStroke.GetProperty("direction").GetInt32(),
                        Length = subStroke.GetProperty("length").GetInt32(),
                        CenterX = subStroke.GetProperty("centerX").GetInt32(),
                        CenterY = subStroke.GetProperty("centerY").GetInt32()
                    });
                }

                referenceCase.Expected.Strokes.Add(referenceStroke);
            }

            foreach (var stroke in element.GetProperty("rawStrokes").EnumerateArray())
            {
                var points = new List<StrokePoint>();
                foreach (var point in stroke.EnumerateArray())
                {
                    points.Add(new StrokePoint(point[0].GetDouble(), point[1].GetDouble()));
                }

                referenceCase.RawStrokes.Add(points);
            }

            foreach (var match in element.GetProperty("expected").EnumerateArray())
            {
                referenceCase.ExpectedMatches.Add(new ReferenceMatch
                {
                    Character = match.GetProperty("character").GetString() ?? string.Empty,
                    Score = ParseScore(match.GetProperty("score"))
                });
            }

            vectors.Cases.Add(referenceCase);
        }

        return vectors;
    }

    /// <summary>
    /// Reads a score out of the vectors. JSON cannot store infinities, so the generator writes the
    /// strings <c>inf</c>, <c>-inf</c> and <c>nan</c> instead.
    /// </summary>
    public static double ParseScore(JsonElement element)
    {
        switch (element.ValueKind)
        {
            case JsonValueKind.Number:
                return element.GetDouble();
            case JsonValueKind.String:
                return element.GetString() switch
                {
                    "inf" => double.PositiveInfinity,
                    "-inf" => double.NegativeInfinity,
                    "nan" => double.NaN,
                    var other => throw new FormatException($"Unsupported score value '{other}'.")
                };
            default:
                throw new FormatException($"Unsupported score value kind '{element.ValueKind}'.");
        }
    }
}

internal sealed class ReferenceDataInfo
{
    public string File { get; init; } = string.Empty;

    public int CharacterCount { get; init; }

    public int SubStrokeByteCount { get; init; }

    public string SubStrokeSha256 { get; init; } = string.Empty;
}

internal sealed class ReferenceCase
{
    public string Name { get; init; } = string.Empty;

    public string? Note { get; init; }

    public double Looseness { get; init; }

    public int Limit { get; init; }

    /// <summary>Whether the JavaScript <c>match()</c> callback was invoked at all (it is not for empty input).</summary>
    public bool CallbackInvoked { get; init; }

    public List<IReadOnlyList<StrokePoint>> RawStrokes { get; } = new();

    public ReferenceAnalysis Expected { get; init; } = new();

    public List<ReferenceMatch> ExpectedMatches { get; } = new();

    public ReferenceCounters Counters { get; init; } = new();
}

internal sealed class ReferenceAnalysis
{
    /// <summary>left, top, right, bottom.</summary>
    public List<double> Bounds { get; } = new();

    public int SubStrokeCount { get; init; }

    public List<ReferenceStroke> Strokes { get; } = new();
}

internal sealed class ReferenceStroke
{
    public List<int> PivotIndexes { get; } = new();

    public List<ReferenceSubStroke> SubStrokes { get; } = new();
}

internal sealed class ReferenceSubStroke
{
    public int Direction { get; init; }

    public int Length { get; init; }

    public int CenterX { get; init; }

    public int CenterY { get; init; }
}

internal sealed class ReferenceMatch
{
    public string Character { get; init; } = string.Empty;

    public double Score { get; init; }
}

internal sealed class ReferenceCounters
{
    public int Characters { get; init; }

    public int SubStrokes { get; init; }
}

internal sealed class ReferenceCurve
{
    public string Name { get; init; } = string.Empty;

    public List<double> Arguments { get; } = new();

    public List<ReferenceCurveSample> Samples { get; } = new();
}

internal sealed class ReferenceCurveSample
{
    public double X { get; init; }

    public List<double> Solutions { get; } = new();

    public double FirstSolution { get; init; }
}
