using System;
using System.IO;

namespace HanziLookup.Tests;

/// <summary>Locations of the test inputs, which the test project copies next to the test assembly.</summary>
internal static class TestPaths
{
    public static string TestDataDirectory => Path.Combine(AppContext.BaseDirectory, "TestData");

    public static string DataFile => Path.Combine(TestDataDirectory, "mmah.json");

    /// <summary>The digits / Latin letters / punctuation repository.</summary>
    public static string AlphanumericFile => Path.Combine(TestDataDirectory, "alnum.json");

    public static string ReferenceVectorsFile => Path.Combine(TestDataDirectory, "reference-vectors.json");

    /// <summary>Throws a helpful exception when an input file is missing.</summary>
    public static string Require(string path, string what)
    {
        if (!File.Exists(path))
        {
            throw new FileNotFoundException(
                $"{what} was not found at '{path}'. The tests expect it to be copied next to the test " +
                "assembly (see HanziLookup.Tests.csproj). The character data can be obtained as described " +
                "in data/README.md, and the reference vectors are generated by " +
                "tools/reference/generate-reference-vectors.mjs.",
                path);
        }

        return path;
    }
}
